chinese translation
blushiemagic/MagicStorage pull request #214
Opened 2022-09-09 07:05 UTC by Zomty

2022-09-09 09:22 UTC, ExterminatorX99 requested changes

2022-09-09 09:22 UTC, ExterminatorX99 commented on Localization/zh-Hans.hjson
> +            '''
Inconsistent usage of spaces and tabs

2022-09-09 09:22 UTC, ExterminatorX99 commented on Localization/zh-Hans.hjson
> +		    ClearItemsButton: "清除所有物品"
Inconsistent tabs and spaces

2022-09-25 02:13 UTC, Zomty commented
fixed bug where tabs were automatically replaced with spaces when I copy-paste text

2022-10-08 05:59 UTC, closed without merging